### ISSUE TITLE
BUG: Run 실행시 Team2Service에 대한 빈 정의가 안되어 있어 발생하는 에러

### ISSUE THREAD

**Issue by DONGUK777** [DE32FinalTeam2/JavaWithKafka#8]
에러 코드
```bash
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-10-25T15:13:53.984+09:00 ERROR 992886 --- [socket] [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field team2Service in com.websocket.socket.controller.GreetingController required a bean of type 'com.websocket.service.Team2Service' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'com.websocket.service.Team2Service' in your configuration.
```
### 이슈 설명
`GreetingController`에서 `@Autowired`를 통해 `Team2Service` 빈을 주입하려고 시도했지만, `Team2Service` 빈이 등록되지 않아 애플리케이션 시작이 실패합니다.

**Comment by EstherCho-7** [comment]
- https://sumni.tistory.com/201
참고하시면 좋을 듯 합니다

**Comment by DONGUK777** [comment]
위 내용 참고해서 `@SpringBootApplication(scanBasePackages = {"com.websoket.service"})` 추가 후 실행했지만,
다음과 같은 에러가 새로 발생했습니다.
```bash
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-10-25T15:22:47.450+09:00 ERROR 1003265 --- [socket] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception with message: Failed to parse mapping resource: 'file [/home/tommy/code/JavaWithKafka/bin/main/mappers/Team2Mapper.xml]'
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.13.jar:6.1.13]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.13.jar:6.1.13]
```

**Comment by GITSangWoo** [comment]
새로 CRUD 전용으로 controller.java 파일을 추가해서  mapping 하는 방법을 추천드립니다.
